### ISSUE TITLE
`authToken` always InvalidParameters, It's still Work?

### ISSUE THREAD

**Issue by nyancodeid** [apriady/ovoid-nodejs#1]
After 2 step phone and OTP on step 3 `loginSecurityCode` always return `InvalidParameters` error. 

```
InvalidParameters: Invalid parameters
    at ovoidError (/media/ryanaunur/Project/ovo-cli/node_modules/ovoid/src/helper/errors.js:90:39)
    at rpOvo.catch.err (/media/ryanaunur/Project/ovo-cli/node_modules/ovoid/src/helper/request.js:23:7)
```

`accessToken` after OTP not always require security PIN
```
{ mobile: '085111222333',
  message: 'This account don\'t have security code yet',
  email: 'youremail@gmail.com',
  fullName: 'YOUR NAME',
  isEmailVerified: true,
  isSecurityCodeSet: false,
  updateAccessToken: '9699d68a5a6b4f358bf22b57f8e7faab' }
```

**Comment by lintangtimur** [comment]
is your account already set a security code?

**Comment by nyancodeid** [comment]
It should be already set :smile: 

ok next problem came from unclear documentation. I already working on my PR. 

I will close this issue, Thanks
